// Rotating placeholder copy for the chat message input — one is picked at random per session
export const CHAT_INPUT_PLACEHOLDERS: string[] = [
  "✨ Make it yours...",
  "🎙️ Say it your way",
  "🌈 Share what's happening",
  "💭 Got a thought? Drop it here",
  "📸 Turn moments into memories",
  "🚀 Start something worth sharing",
  "⭐ What's your story today?",
  "🎉 Bring your moment to life",
  "💫 Leave a little piece of your day",
  "🌟 Something on your mind? We're all ears",
  "🎨 Express yourself in any format",
  "👀 Show us what's caught your eye",
  "🪄 Create a moment",
  "🔥 What's your latest obsession?",
  "🌊 Let it flow... words, pics, or clips",
  "Drop a message... or share a pic/video 📸🎥",
  "Say something... or flex your latest photo/video 😎📸",
  "What's on your mind? Send a message or drop a photo/video ✨",
  "Start the convo... or upload a photo/video to share the vibe 📸🎬",
  "Share a thought, snap, or video... we'd love to see it! 📸🎥✨",
  "Drop your vibe... pics, clips, or thoughts welcome",
  "What's the tea? Spill it here or share a snap",
  "Say it, show it, share it",
  "Your moment starts here... type, snap, or record",
  "Got something worth sharing? We're listening",
  "Drop a thought. Post a vibe. Share the moment.",
  "Paint the story your way... words, photos, or videos",
  "What's living rent-free in your mind today?",
  "Show us your world... one message, photo, or video at a time",
  "Thoughts? Memories? Moments? Drop them below.",
  "Share your vibe... words, pics, or moments 🎬",
  "Drop a vibe, not just a message",
  "What's your main character moment today?",
  "Drop a mood, memory, or masterpiece",
  "Tell it. Show it. Own it.",
  "Drop a vibe",
  "Share a moment",
  "What's new?",
  "Show & tell",
  "Your turn",
  "Drop something cool",
  "Share your spark",
  "What's the vibe?",
  "Express yourself",
  "Say it. Show it.",
  "Snap & share",
  "Say less. Share more.",
  "Post your mood",
  "Drop a moment",
  "Share the energy",
  "Catch the vibe",
  "Spill the tea",
  "Leave your mark",
  "Start the buzz",
  "Bring the vibes",
  "Share your scene",
  "What's popping?",
  "Make it count",
  "Own the moment",
  "Tell your story",
  "Show your world",
  "Drop a gem",
  "Add your flavor",
  "Pass the vibe check",
  "Create the moment",
  "Keep it real",
  "What's your mood?",
  "Share the magic",
  "Spark a convo",
  "What's your take?",
  "Say it.",
  "Share it.",
  "Show it.",
  "Drop it.",
  "Upload it.",
  "Tell us.",
  "Let's see.",
  "Your move.",
  "Go for it.",
  "We're listening.",
  "What's up?",
  "Got vibes?",
  "Talk to us.",
  "Share away.",
  "Make waves.",
  "Stay iconic.",
  "Drop magic.",
  "Be seen.",
  "Be heard.",
  "Be you.",
]

export function getRandomChatPlaceholder(): string {
  return CHAT_INPUT_PLACEHOLDERS[Math.floor(Math.random() * CHAT_INPUT_PLACEHOLDERS.length)]
}
